### ISSUE TITLE
Add to Rubygems

### ISSUE THREAD

**Issue by thomasmeeus** [raphink/github-readme-generator#1]
Hi @raphink 

I saw your presentation at cfgmgmtcamp yesterday and would like to use this readme generator. Is there a pre-build gem available somewhere (on Rubygems perhaps)? 
Thx

**Comment by raphink** [comment]
Hi @thomasmeeus, @mfournier was actually the one who gave the presentation yesterday in my stead since I couldn't be there (thanks again @mfournier).

I just pushed the gem to rubygems.
